version: '3.0'
services:
  streetmerchant-shop-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetmerchant-shop-bot
    hostname: streetmerchant-shop-bot
    env_file: .env
    # ports:
    #   - 7997:7997
